#!/usr/bin/env bash

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Define the custom header configuration
custom_header_config="add_header X-Served-By \$hostname;"

# Add the custom header configuration to the Nginx configuration file
sudo sed -i "/^http {/a \\t$custom_header_config" /etc/nginx/nginx.conf

# Restart Nginx to apply the changes
sudo systemctl restart nginx
