#!/usr/bin/env bash
# Installs and sets up HAProxy on lb-01 server

# Install required packages
apt-get update
apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.6
apt-get update
apt-get install -y haproxy=2.6.*

# Enable HAProxy service
systemctl enable haproxy

# Write HAProxy configuration
cat <<EOF > /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend load_balancer
    bind *:80
    mode http
    default_backend web_servers
    http-request add-header X-Served-By %[hostname]

backend web_servers
    balance roundrobin
    server web-01 54.144.154.101:80 check
    server web-02 52.3.246.209:80 check
EOF

# Restart HAProxy service
systemctl restart haproxy
