#!/usr/bin/env bash
# Script to create an RSA key pair with specific requirements

passphrase="betty"

# Generate RSA key pair with specified requirements
echo "Generating public/private rsa key pair..."
ssh-keygen -t rsa -b 4096 -N $passphrase -f ~/.ssh/school

# Display additional information
echo "Your identification has been saved in school."
echo "Your public key has been saved in school.pub."
echo "The key fingerprint is:"
ssh-keygen -lf ~/.ssh/school.pub
echo "The key's randomart image is:"
ssh-keygen -lvf ~/.ssh/school
